### ISSUE TITLE
LDAP login works when the LDAPIdenitityProvider configuration uses the simplest (TBD) LDAP options

### ISSUE THREAD

**Issue by cfryanr** [vmware-tanzu/pinniped#338] opened 2021-01-16 00:00 UTC
**Purpose:** After arriving at the LDAP login page, I would like to be able to complete the login by using my correct LDAP account username and password.

**Given** that I have an `LDAPIdentityProvider` configured with Pinniped
**And given** I have only used the most straightforward configuration options (specific options TBD)
**And given** I have configured my kubeconfig to use pinniped
**And given** I run `kubectl`, been presented with the LDAP login page
**When** I enter my correct username and password and submit the form
**Then** My browser is redirected to the page that says "login was successful and you may close the browser"
**And Then** My kubectl command continues successfully using my identity from LDAP

Notes: For this issue, we should choose whichever LDAP configuration is the easiest to implement and only support those configuration options as part of this issue. Other configuration options that we wish to support should be added as new issues.

**Comment by mattmoyer** [comment] 2021-02-23 22:58
I think this is a duplicate of https://github.com/vmware-tanzu/pinniped/issues/440. We did make some slightly different design decisions but it's the same core story, I think.

**Closed by mattmoyer** 2021-02-23 22:58 UTC
Labels: priority/undecided
