### ISSUE TITLE
Bitnami Helm Chart not working with impersonation proxy service

### ISSUE THREAD

**Issue by wolffberg** [vmware-tanzu/pinniped#1220] opened 2022-07-06 08:32 UTC
This issue is a link to https://github.com/bitnami/charts/issues/11054 in case coordination is needed to create the best solution as the impersonation proxy service is created by Pinniped and not the Helm Chart.

_Short description_
In a Kubernetes cluster without a `kube-controller-manager` the impersonation proxy service does not have any targets and the `pinniped-concierge` pod does not expose port `8444`.

**Comment by agtogna** [comment] 2023-01-09 11:29
the service is created with an empty `app= ''` whether `ImpersonationProxy` is of service `LoadBalancer` or `ClusterIP` .

**Comment by wolffberg** [comment] 2023-01-09 11:40
We ended up setting the the service type to `None` using `credentialIssuerConfig` and creating the service outselves targeting the correct pods.

**Comment by cfryanr** [comment] 2023-01-09 20:20
I haven't looked at the Bitnami helm charts in detail, but I'm unclear on why this works fine with Pinniped's own YAML manifests but does not work with Bitnami's helm chart. I would guess that the Bitnami helm chart is not copying some important setting from Pinniped's own YAML manifests. Anyone checked this yet?

**Comment by agtogna** [comment] 2023-01-10 12:07
the problem seems to be that:
- in [impersonator_config.go](https://github.com/vmware-tanzu/pinniped/blob/v0.21.0/internal/controller/impersonatorconfig/impersonator_config.go) the ONLY label which is used for the LoadBalancer/ClusterIP service selector is "app:"
- in the official deployment pinniped YAMLs the default labels are "app: pinniped-concierge" (`labels: {"app":"pinniped-concierge"}`) so they get picked up by the impersonator controller
- in the Bitnami Helm chart's YAMLs the labels are set differently (`labels: {"app.kubernetes.io/part-of":"pinniped", "app.kubernetes.io/component": "concierge", "app.kubernetes.io/instance": "release-name"}`), the impersonator controller does not find the `app` label and thus does not work

the problem seems to be in impersonator_config.go and in it not using the labels as defined in `pinniped.yaml`; in line 57 there's a const definition for `appLabelKey= "app"` which is then used later in lines 469 and 514 to create the Service selector:
`Selector: map[string]string{appLabelKey: appNameLabel}`

**Comment by agtogna** [comment] 2023-01-10 12:12
I don't think the Bitnami chart is wrong in changing the labels, I think Pinniped should read the labels from pinniped.yaml and set the Service selector based on them; hardcoding the label key in the code is too binding (IMHO)

**Comment by cfryanr** [comment] 2023-01-10 17:32
Thanks for investigating! That’s awesome that you found the cause.

In this case, Bitnami helm charts should not be using different labels for this purpose. Unfortunately, that’s not supported by Pinniped at this time. The Helm charts are welcome to add additional labels if they wish, but the `app` label is not optional. The value of the label is configurable, but the key of the label is hardcoded, as you found.

Pinniped was designed to work with its own YAML manifests as included in the source code repo as ytt templates and as included in the github releases as attachments. It would not be possible for Pinniped to be so flexible as to support every potential manifest change that could exist in 3rd party configurations/deployments.

**Comment by agtogna** [comment] 2023-01-11 09:27
I've created a PR on bitnami/pinniped:
https://github.com/bitnami/charts/pull/14278

**Comment by cfryanr** [comment] 2023-01-24 16:22
I see that your bitnami PR was merged. Thank you so much for finding and fixing this! Closing this issue for now.

**Closed** 2023-01-24 16:22 UTC
Labels: bug, state/accepted
