### ISSUE TITLE
Support mTLS for LDAP configuration

### ISSUE THREAD

**Issue by mhoshi-vm** [vmware-tanzu/pinniped#1571] opened 2023-07-06 01:32 UTC
**Is your feature request related to a problem? Please describe.**

Currently we only support one way TLS verification with password authentication.
However (although still rare) LDAP does support mTLS configuration.

https://ltb-project.org/documentation/openldap_ssl_tls_mutual_authentication.html

Dex has this configured so this will be a hurdle for customers to migrate out of it

https://github.com/dexidp/dex/issues/1277

**Describe the solution you'd like**

for TLSSpec there should be a field for client certificate and key.

**Describe alternatives you've considered**

No alternative if the LDAP server only accepts mTLS

**Comment by cfryanr** [comment] 2023-07-06 16:23
@mhoshi-vm Is this a duplicate of https://github.com/vmware-tanzu/pinniped/issues/1425, or do you see some difference in your needs versus what is described in that other issue?

**Comment by cfryanr** [comment] 2023-07-20 17:16
Thanks for creating this issue @mhoshi-vm. I didn't hear back from you, so I'm going to assume that this is a duplicate of #1425. Please let us know if there are any differences in what you were requesting, and we can reopen this issue.

**Closed by cfryanr** 2023-07-20 17:16 UTC
